language: node_js
node_js:
  - node
services:
  - postgresql

before_install:
  - psql -c 'create database protestdb' -U postgres
install:
  - npm i -g sequelize-cli
  - npm install
cache:
  directories:
    - "node_modules"
script:
  - npm run test-dev
after_success:
  - npm run coverage
